name: Run API and App Tests
on:
  push:
  pull_request:
    branches: [main]
  # This is also a reusable workflow that can be called from other workflows
  workflow_call:
jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          python -m pytest --cov=.
  test-app:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
    defaults:
      run:
        shell: bash
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - name: Use latest Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
      - name: Run npm CI
        run: npm ci
      - name: Test app
        run: npm run test -- --no-color --run
